name: deliverzler
description: Deliverzler
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
  flutter_native_splash: 
  flutter_localizations:
    sdk: flutter
  intl: 

  #StateManagement & DI
  flutter_hooks: 
  hooks_riverpod: 
  riverpod_annotation: 
  get_it: 

  #FP
  fpdart: 
  rxdart:

  #Connectivity
  connectivity_plus: 

  #Location
  location: 
  geolocator: 
  google_maps_flutter: 
  flutter_polyline_points: 

  #Apis
  dio:

  #Firebase
  firebase_core: 
  cloud_firestore: 
  firebase_auth: 
  firebase_storage: 
  firebase_messaging:

  #LocalStorage
  shared_preferences: 
  sqflite: 
  flutter_cache_manager: 
  image_picker: 
  #Images
  cached_network_image: 
  lottie: 

  #Utils
  freezed_annotation: 
  equatable: 
  fast_immutable_collections: 
  flutter_fadein: 
  uuid: 
  url_launcher: 
  flutter_local_notifications: 
  timeago: 

  #Widgets
  fluttertoast: 
  qr_flutter: 
  material_floating_search_bar: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.3.2
  riverpod_generator: ^1.0.4
  freezed: ^2.2.0
  mockito: ^5.3.2

flutter_icons:
  image_path_android: "assets/images/core/icon.png"
  image_path_ios: "assets/images/core/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#121B24"
  adaptive_icon_foreground: "assets/images/core/icon_adaptive_fore.png"

flutter_native_splash:
  color: "#FAFAFA"
  color_dark: "#303030"
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  android_12:
    image: "assets/images/welcome/transparent_splash_icon.png"
    image_dark: "assets/images/welcome/transparent_splash_icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/welcome/
    - assets/images/login/
    - assets/images/core/
    - assets/images/core/dialog_widget_icons/
    - assets/images/app_icons/
    - assets/images/app_icons/screens_icons/
    - assets/images/app_icons/languages_icons/
    - assets/json/
    - assets/json/map_styles/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
        - asset: assets/fonts/poppins_bold.ttf
          weight: 900
    - family: tajawal
      fonts:
        - asset: assets/fonts/tajawal.ttf
        - asset: assets/fonts/tajawal_bold.ttf
          weight: 900